import { emptyContent, type BusinessType, type PostContent } from "./types";

/**
 * Neutral placeholder content used only for template thumbnails. No invented
 * company, person or customer data: labels describe the business type itself.
 */
const BY_TYPE: Partial<Record<BusinessType, Partial<PostContent>>> = {
  travel_agency: {
    title: "Summer offer",
    subject: "Destination",
    location: "Hotel name",
    price: "590",
    date: "August",
    meta1: "7 nights",
    additionalText: "Limited places",
    services: ["Flights", "Hotel", "Transfer"],
    cta: "Send a message",
  },
  real_estate: {
    title: "New listing",
    subject: "City centre",
    price: "180000",
    meta1: "3 rooms",
    meta2: "92 m2",
    date: "Available now",
    additionalText: "Viewings this week",
    services: ["Balcony", "Parking", "Elevator"],
    cta: "Book a viewing",
  },
  car_dealership: {
    title: "In stock now",
    subject: "Model",
    price: "18900",
    meta1: "2022",
    meta2: "45 000 km",
    date: "Financing available",
    additionalText: "Full service history",
    services: ["Warranty", "Trade in"],
    cta: "Book a test drive",
  },
  restaurant: {
    title: "Today's special",
    subject: "Menu",
    price: "12",
    location: "City centre",
    date: "This week",
    additionalText: "Reservations recommended",
    services: ["Dine in", "Takeaway"],
    cta: "Reserve a table",
  },
  retail: {
    title: "New arrival",
    subject: "Category",
    price: "49",
    meta1: "-20%",
    date: "Until Sunday",
    additionalText: "While stock lasts",
    services: ["Delivery", "Returns"],
    cta: "Shop now",
  },
  hotel: {
    title: "Stay offer",
    subject: "Room type",
    location: "City or area",
    price: "120",
    date: "This season",
    meta1: "2 nights",
    additionalText: "Breakfast included",
    services: ["Breakfast", "Parking", "Pool"],
    cta: "Check availability",
  },
  beauty: {
    title: "New treatment",
    subject: "Service",
    price: "35",
    date: "This week",
    additionalText: "Limited appointments",
    services: ["Consultation", "Styling"],
    cta: "Book your spot",
  },
  fitness: {
    title: "Membership offer",
    subject: "Programme",
    price: "29",
    date: "This month",
    additionalText: "First week free",
    services: ["Group classes", "Trainer"],
    cta: "Start your trial",
  },
  healthcare: {
    title: "Check up offer",
    subject: "Service",
    price: "49",
    date: "This week",
    additionalText: "Appointments available",
    services: ["Consultation", "Follow up"],
    cta: "Book an appointment",
  },
  construction: {
    title: "Project offer",
    subject: "Service",
    price: "On request",
    date: "Available now",
    additionalText: "Free site visit",
    services: ["Materials", "Warranty"],
    cta: "Request an estimate",
  },
  cleaning: {
    title: "Cleaning offer",
    subject: "Service",
    price: "39",
    date: "This week",
    additionalText: "Flexible hours",
    services: ["Deep clean", "Eco products"],
    cta: "Book a cleaning",
  },
  events: {
    title: "Event package",
    subject: "Event type",
    location: "Venue",
    price: "On request",
    date: "Open dates",
    additionalText: "Full planning included",
    services: ["Catering", "Decoration"],
    cta: "Check your date",
  },
  education: {
    title: "Course starting",
    subject: "Course",
    price: "150",
    date: "Next month",
    additionalText: "Small groups",
    services: ["Materials", "Certificate"],
    cta: "Enrol now",
  },
  professional_services: {
    title: "Service offer",
    subject: "Service",
    price: "On request",
    date: "This month",
    additionalText: "First consultation free",
    services: ["Consultation", "Support"],
    cta: "Get in touch",
  },
  ecommerce: {
    title: "New arrival",
    subject: "Category",
    price: "49",
    meta1: "-20%",
    date: "Until Sunday",
    additionalText: "Ships today",
    services: ["Free shipping", "Returns"],
    cta: "Shop now",
  },
  automotive_service: {
    title: "Service offer",
    subject: "Service",
    price: "59",
    date: "This week",
    additionalText: "Same day slots",
    services: ["Diagnostics", "Warranty"],
    cta: "Book a service",
  },
  other: {
    title: "Your headline",
    subject: "Product or service",
    price: "99",
    date: "This month",
    additionalText: "Short supporting line",
    services: ["Feature one", "Feature two"],
    cta: "Get in touch",
  },
};

export function placeholderContent(type: BusinessType): PostContent {
  return { ...emptyContent, services: [], ...(BY_TYPE[type] ?? BY_TYPE.other) } as PostContent;
}
